<template>
  <!-- SECURITY: v-html can be dangerous if the content comes from a user.
       Here, it is safe because the content is generated by our own trusted AI service. -->
  <div class="markdown-content" v-html="renderedHtml"></div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import MarkdownIt from 'markdown-it'

// Define the props this component accepts
const props = defineProps<{
  content: string
}>()

// Initialize the markdown-it renderer
const md = new MarkdownIt()

// Create a computed property that will automatically re-render the HTML
// whenever the 'content' prop changes.
const renderedHtml = computed(() => {
  return md.render(props.content || '') // Render the content prop as HTML
})
</script>

<style scoped>
/* Add some basic styling for the rendered HTML elements */
.markdown-content :deep(h1),
.markdown-content :deep(h2),
.markdown-content :deep(h3) {
  margin-top: 1.5rem;
  margin-bottom: 1rem;
  line-height: 1.3;
  font-weight: 600;
}

.markdown-content :deep(ul) {
  padding-left: 1.5rem;
  margin-bottom: 1rem;
}

.markdown-content :deep(li) {
  margin-bottom: 0.5rem;
}
</style>
